PROGRAM MAIN
USE pars
USE gaussquad
IMPLICIT NONE
 REAL(DP)::LPOLY(0:NMAX,0:LMAX,1:NGAUSS),LOGANL(0:NMAX,0:LMAX)!l_nl^{alpha}
 REAL(DP)::X(1:NGAUSS),W(1:NGAUSS),V(1:NGAUSS)!Gauss-hermite integeral points, weight, and potential V
 REAL(DP)::CMAT(0:NMAX,0:NMAX),TMAT(0:NMAX,0:NMAX),HMAT(0:NMAX,0:NMAX)!Columb, Kinetic, H matrix
 REAL(DP)::HD(0:NMAX),HE(0:NMAX),TAU(0:NMAX),HTEMP(0:NMAX,0:NMAX)!HD STORES EIGENVALUES AFTER DIAGONALIZATION 
 REAL(DP)::ALPHA,SUMS, BSTEP,BMIN,BB
 INTEGER::L!ANGULAR MOMENTUM
 INTEGER::I,K,NI,NJ,NR,LWORK,INFO,BTOTAL,IB,JN,ABSORB
 REAL(DP),ALLOCATABLE::EGS(:)!GROUND STATE ENERGIES(n)
 REAL(DP),ALLOCATABLE::WORK(:)!WORKING SPACE FOR DIAGONALIZATION
 INTEGER::NRS(5)!NR=2,5,10,20,50
 CHARACTER::UPLO
 CHARACTER(LEN=100)::NAM,INTAC,QUAD,KEYWOR
!
 ALPHA=0.0D0;L=0;NR=50!l and nmax value
 NRS=(/2,5,10,20,50/)
 BTOTAL=20;BSTEP=0.1D0;BMIN=0.0d0!total steps, steplength, beginning point of b 
 HBAR=1.0D0;MASS=1.0D0;HBARM=1.0D0;BOSC=1.0D0;HBOMG=1.0d0!initialization
 UPLO='U'
 HMAT(:,:)=0.0D0
 TMAT(:,:)=0.0D0
 CMAT(:,:)=0.0D0
 INTAC='OSC'
 QUAD='Laguerre'
!
 ABSORB=1
! READ("INPUT",*)KEYWOR
 LWORK=NMAX*NMAX
 ALLOCATE(WORK(LWORK))
 ALLOCATE(EGS(5))
!
 IF((NR.GT.NMAX).OR.(L.GT.LMAX))STOP 'TOO LARGE NR OR L'
 IF((TRIM(QUAD)=='Hermite').AND.(MOD(NGAUSS,2)==0))&
 STOP 'NGAUSS SHOULD BE ODD WHEN USING HERMITE'
!
 IF(ABSORB==1)THEN!POTENTIAL IS ABSORBED INTO X^2dX IN THE INTEGRAL
    IF((TRIM(QUAD)=='Laguerre').AND.(TRIM(INTAC)=='COL')) ALPHA=L
    IF((TRIM(QUAD)=='Laguerre').AND.(TRIM(INTAC)=='OSC')) ALPHA=L+1.5D0
    CALL cpquad(NGAUSS,ALPHA,TRIM(QUAD),W,X)!FIND INTEGRAL POINTS AND WEIGHTS
    CALL LNLS(X,LPOLY,TRIM(QUAD))!CONSTRUCT LAGUERRE
    CALL ANLS(LOGANL)!CALCULATE ANL COEEFICIENTS
    CALL TMATRX(NR,L,TMAT)!CONSTRUCT<NL|T|N'L> 
    CALL CMATRX(NR,L,X,W,LPOLY(:,L,:),LOGANL,TRIM(INTAC),TRIM(QUAD),CMAT)!CONSTRUCT<NL|V|N'L>
 ELSE!V AS INPUT
    IF(TRIM(QUAD)=='Laguerre') ALPHA=L+0.5D0
    CALL cpquad(NGAUSS,ALPHA,TRIM(QUAD),W,X)!FIND INTEGRAL POINTS AND WEIGHTS
    CALL LNLS(X,LPOLY,TRIM(QUAD))!CONSTRUCT LAGUERRE 
    CALL ANLS(LOGANL)!CALCULATE ANL COEEFICIENTS
    CALL TMATRX(NR,L,TMAT)!CONSTRUCT<NL|T|N'L>
    CALL INTACT(X,V,TRIM(INTAC),TRIM(QUAD))
    CALL VMATRX(NR,L,X,W,V,LPOLY(:,L,:),LOGANL,TRIM(QUAD),CMAT)
 ENDIF

!OUTPUT BEGIN

 NAM=TRIM(QUAD)//'.'//TRIM(INTAC)!output file name
 OPEN(7,FILE=TRIM(NAM))
80   FORMAT(A1,4X,A2,4X,I2,12X,I2,12X,I2,12X,I2,12X,I2,12X)
90   FORMAT(F3.1,4X,F12.9,2X,F12.9,2X,F12.9,2X,F12.9,2X,F12.9)
WRITE(7,*) "GAUSS-",TRIM(QUAD)," INTEGRAL IS USED"
WRITE(7,80)'b=','N=',2,5,10,20,50
!T(OMEGA)=OMEGA*T(1); V(B)=B*V(1);H(B)=B^2/(HBAR/M)*T(1)-B*1/(R*B)
 DO IB=1,BTOTAL!CHANGE B
    BB=BMIN+IB*BSTEP
    IF(TRIM(INTAC)=="OSC")THEN
       HMAT(:,:)=BB**2/HBARM*TMAT(:,:)+BB**2*CMAT(:,:)!CONSTRUCT<NL|H|N'L>, oscillator potential
    ELSEIF(TRIM(INTAC)=="COL")THEN
       HMAT(:,:)=BB**2/HBARM*TMAT(:,:)-BB*CMAT(:,:)!CONSTRUCT<NL|H|N'L>, columb potential
    ENDIF
    DO JN=1,5!CHANGE NMAX
       HTEMP=HMAT!DSYTRD WOULD CHANGE INPUT MATRIX
       NI=NRS(JN)
       CALL DSYTRD(UPLO,NI+1,HTEMP(0:NI,0:NI),NI+1,HD(0:NI),HE(0:NI-1),TAU(0:NI-1),WORK,LWORK,INFO)
       CALL DSTERF(NI,HD(0:NI),HE(0:NI-1),INFO)!DIAGONALIZATION
       EGS(JN)=HD(0)
    ENDDO
    WRITE(7,90)BB,EGS(1),EGS(2),EGS(3),EGS(4),EGS(5)
 ENDDO
 CLOSE(7)
!TESTS
! if(.false.)then
!    sums=0.0d0
!    do ib=ngauss/2+1,ngauss
!       sums=sums+w(ib)*x(ib)
!    enddo
!    write(*,*)sums
!  endif
!
!IF(.false.)THEN
! V(:)=1.0D0
! CALL VMATRX(NR,L,X,W,V,LPOLY(:,L,:),LOGANL,CMAT)
! WRITE(*,*)CMAT(65:70,65:70)
!ENDIF
!
!IF(.FALSE.)THEN
! DO I= 1, NR
!    HMAT(I,I)=sqrt(I*1.0D0)
!    HMAT(I-1,I)=0.5D0
!    HMAT(I,I-1)=0.5D0
! ENDDO
! WRITE(*,*)CMAT(0:NR,0:NR)
!ENDIF
END PROGRAM

