PROGRAM MAIN
USE pars
USE gaussquad
IMPLICIT NONE
 REAL(DP)::LPOLY(0:NMAX,0:LMAX,1:NGAUSS),LOGANL(0:NMAX,0:LMAX)!l_nl^{alpha}
 REAL(DP)::X(1:NGAUSS),W(1:NGAUSS),V(1:NGAUSS)!Gauss-hermite integeral points, weight, and potential V
 REAL(DP)::CMAT(0:NMAX,0:NMAX),TMAT(0:NMAX,0:NMAX),HMAT(0:NMAX,0:NMAX)!Columb, Kinetic, H matrix
 REAL(DP)::HD(0:NMAX),HE(0:NMAX),TAU(0:NMAX)!HD STORES EIGENVALUES AFTER DIAGONALIZATION 
 REAL(DP)::ALPHA,SUMS, BSTEP,BMIN,BB
 INTEGER::L!ANGULAR MOMENTUM
 INTEGER::I,K,NI,NJ,NR,LWORK,INFO,BTOTAL,IB
 REAL(DP),ALLOCATABLE::EGS(:)!GROUND STATE ENERGIES
 REAL(DP),ALLOCATABLE::WORK(:)!WORKING SPACE FOR DIAGONALIZATION
 CHARACTER::UPLO
!
 ALPHA=0.0D0;L=0;NR=50!l and nmax value
 BTOTAL=50;BSTEP=0.1D0;BMIN=0.0d0!total steps, steplength, beginning point of b 
 HBARM=1.0D0;BOSC=1.0D0;HBOMG=1.0d0!initialization
 UPLO='U'
 HMAT(:,:)=0.0D0
 TMAT(:,:)=0.0D0
 CMAT(:,:)=0.0D0
!
 LWORK=NMAX*NMAX
 ALLOCATE(WORK(LWORK))
 ALLOCATE(EGS(1:BTOTAL))
!
 IF((NR.GT.NMAX).OR.(L.GT.LMAX))STOP 'TO LARGE NR OR L'
!
 CALL cpquad(NGAUSS,ALPHA,"Hermite",W,X)!FIND INTEGRAL POINTS AND WEIGHTS
 CALL LNLS(X,LPOLY)!CONSTRUCT LAGUERRE 
 CALL ANLS(LOGANL)!CALCULATE ANL COEEFICIENTS
! CALL INTACT(X,V)
! CALL VMATRX(NR,L,X,W,V,LPOLY(:,L,:),LOGANL,CMAT)
 CALL CMATRX(NR,L,X,W,LPOLY(:,L,:),LOGANL,CMAT)!CONSTRUCT <NL|V|N'L> WHERE V IS COLOUMB INTERACTION
 CALL TMATRX(NR,L,TMAT)!CONSTRUCT<NL|T|N'L>

!T(OMEGA)=OMEGA*T(1); V(B)=B*V(1);H(B)=B^2/(HBAR/M)*T(1)-B*V(1)
 DO IB=1,BTOTAL
    BB=BMIN+IB*BSTEP
    HMAT(:,:)=BB**2/HBARM*TMAT(:,:)-BB*CMAT(:,:)!CONSTRUCT<NL|H|N'L>
    CALL DSYTRD(UPLO,NR+1,HMAT(0:NR,0:NR),NR+1,HD(0:NR),HE(0:NR-1),TAU(0:NR-1),WORK,LWORK,INFO)
    CALL DSTERF(NR,HD(0:NR),HE(0:NR-1),INFO)!DIAGONALIZATION
    EGS(IB)=HD(0)
 ENDDO

100  FORMAT(A10,7X,A1)
200  FORMAT(F7.4,10X,F7.4)
 WRITE(*,100)'G.S.ENERGY','B'
 DO IB=1,BTOTAL
    BB=BMIN+IB*BSTEP
    WRITE(*,200)EGS(IB),BB
 ENDDO
!IF(.true.)THEN
! V(:)=1.0D0
! CALL VMATRX(NR,L,X,W,V,LPOLY(:,L,:),LOGANL,CMAT)
! WRITE(*,*)CMAT(65:70,65:70)
!ENDIF
!
!IF(.FALSE.)THEN
! DO I= 1, NR
!    HMAT(I,I)=sqrt(I*1.0D0)
!    HMAT(I-1,I)=0.5D0
!    HMAT(I,I-1)=0.5D0
! ENDDO
! WRITE(*,*)CMAT(0:NR,0:NR)
!ENDIF
END PROGRAM

