MODULE PARS
 INTEGER,PARAMETER::DP=8
 INTEGER,PARAMETER::NIORB=100,NMORB=40
 INTEGER,PARAMETER::NMAX=1,LMAX=2,JMAX=5,TMAX=1,NSPIN=1
 INTEGER::NUSE,LUSE,NSHELL
 REAL(DP)::BOSC,HBAR2M,HBROMG!OSCILLATOR LENGTH^(-1)
 REAL(DP)::KAPPAR,KAPPAS,V0R,V0S!COEFFICIENT OF THE POTENTIAL 
END MODULE PARS

MODULE BLOCKS
 TYPE BIDX
  INTEGER::L,S,NL,OCC
 END TYPE
 INTEGER::IBLOCK!TOTAL BLOCK NUMBERS
 INTEGER,ALLOCATABLE::B_DEGE(:,:)!PARTICLE NUMBER IN EACH ORBIT IN EACH BLOCK
 TYPE(BIDX),ALLOCATABLE::B_LABEL(:)!QUANTUM NUMBERS CARRIED BY BLOCK LABEL I;N DIMENSION, OCCUPIED NUMBER
END MODULE BLOCKS

MODULE RHOS
USE PARS
 REAL(DP),ALLOCATABLE::RHO_UU(:,:,:)
 REAL(DP),ALLOCATABLE::RHONEW_UU(:,:,:)
END MODULE RHOS

MODULE EIGENS
USE PARS
 REAL(DP),ALLOCATABLE::EVEC_UU(:,:,:)!NMAX,NMAX,IBLOCK
 REAL(DP),ALLOCATABLE::EIGVAL(:,:),EIGVAL_NEW(:,:)!NMAX,ITOTAL
END MODULE EIGENS

MODULE EORDER
USE PARS
 TYPE EINDX
  REAL(DP)::E
  INTEGER ::N,A
 END TYPE
 TYPE(EINDX),ALLOCATABLE::EIGORD(:)!
END MODULE EORDER

MODULE RESHAPED!RESHAPED V, U IN GIVEN AB OR A BLOCK
USE PARS
 REAL(DP),ALLOCATABLE::VTEMP(:,:,:,:)!NMAX,NMAX,NMAX
 REAL(DP),ALLOCATABLE::TTEMP(:,:)!NMAX,NMAX
END MODULE RESHAPED

MODULE TABLES
USE PARS
 REAL(DP),ALLOCATABLE::VMTAB(:,:,:,:)
 INTEGER,ALLOCATABLE ::MLABEL(:,:,:,:,:)
END MODULE TABLES

MODULE TUMATS
USE PARS
 REAL(DP),ALLOCATABLE::TUMAT(:,:,:)
END MODULE TUMATS

MODULE V2MATS
USE PARS
 TYPE V2INX
  INTEGER::N1,N3,L,J
 END TYPE V2INX
 REAL(DP),ALLOCATABLE::V2B_UU(:,:)
 INTEGER,ALLOCATABLE::JORB(:,:,:,:)
 TYPE(V2INX),ALLOCATABLE::JLABEL(:)
END MODULE V2MATS

MODULE VMEANS
USE PARS
 REAL(DP),ALLOCATABLE::VMEAN_UU(:,:)
END MODULE VMEANS

MODULE HMATS
USE PARS
 REAL(DP),ALLOCATABLE::HMAT_UU(:,:)
END MODULE HMATS

FUNCTION NLIMIT(L,N) RESULT(RES)!FIND THE LARGEST POSSIBLE N VALUE FOR A GIVEN L
USE PARS
IMPLICIT NONE
 INTEGER::L,N,RES
 RES=MIN((NSHELL-1-L)/2,NMAX)
 RETURN
END FUNCTION NLIMIT

FUNCTION SSTART(L) RESULT(RES)
IMPLICIT NONE
 INTEGER::L,RES
 IF(L==0) RES=1
 IF(L> 0) RES=0
 RETURN
END FUNCTION SSTART

FUNCTION MAX_DEGE(N,I) RESULT(RES)
USE BLOCKS
IMPLICIT NONE
 INTEGER::N,I,RES
 RES=2*(B_LABEL(I)%L+B_LABEL(I)%S)
 RETURN
END FUNCTION MAX_DEGE

FUNCTION STATE_TOTAL(LUSE,NSHELL) RESULT(RES)!FIND HF STATES NUMBER -1
IMPLICIT NONE
 INTEGER::LUSE,NSHELL,RES
 INTEGER::L,N,S,TOTAL,NLIMIT
 TOTAL=0
 DO L=0,LUSE
    !N=((NSHELL-1)-L)/2+1
    N=NLIMIT(L,NSHELL)+1
    IF(L==0)TOTAL=TOTAL+N
    IF(L> 0)TOTAL=TOTAL+N*2
 ENDDO
 RES=TOTAL-1
 RETURN
END FUNCTION STATE_TOTAL

FUNCTION BLOCK_TOTAL(LUSE) RESULT(RES)!FIND HF STATES NUMBER -1
IMPLICIT NONE
 INTEGER::LUSE,N,RES
 INTEGER::L,TOTAL
 TOTAL=0
 DO L=0,LUSE
    IF(L==0)TOTAL=TOTAL+1
    IF(L> 0)TOTAL=TOTAL+2
 ENDDO
 RES=TOTAL-1
 RETURN
END FUNCTION BLOCK_TOTAL

FUNCTION MS_TOTAL(LUSE,NSHELL) RESULT(RES)!BASIS NUMBER IN M SCHEME
IMPLICIT NONE
 INTEGER::LUSE,NSHELL,RES,NLIMIT
 INTEGER::L,N,S,START,SMAX,JM,TOTAL
 TOTAL=0
 SMAX=1
 DO L=0,LUSE
    !N=((NSHELL-1)-L)/2+1
    N=NLIMIT(L,NSHELL)+1
    IF(L==0)START=1
    IF(L> 0)START=0
    DO S=START,SMAX
       JM=2*(L+S)
       TOTAL=TOTAL+JM*N
    ENDDO
 ENDDO
 RES=TOTAL*2!different isospin
 RETURN
END FUNCTION MS_TOTAL

FUNCTION V2_TOTAL(LUSE,NSHELL) RESULT(RES)!NUMBERS OF POSSIBLE (N1,N3,L,J) COMBINATION
IMPLICIT NONE
 INTEGER::LUSE,NSHELL,RES,NLIMIT
 INTEGER::L,N,S,START,TOTAL
 TOTAL=0
 DO L=0,LUSE
    !N=((NSHELL-1)-L)/2+1
    N=NLIMIT(L,NSHELL)+1
    IF(L==0)TOTAL=TOTAL+N**2
    IF(L> 0)TOTAL=TOTAL+2*N**2
 ENDDO
 RES=TOTAL
 RETURN
END FUNCTION V2_TOTAL
