SUBROUTINE LOADS
USE PARS
USE BLOCKS
USE RHOS
USE EIGENS
USE EORDER
USE RESHAPED
USE TABLES
USE TUMATS
USE V2MATS
USE VMEANS
USE HMATS
IMPLICIT NONE
 INTEGER::BLOCK_TOTAL,STATE_TOTAL,MS_TOTAL,V2_TOTAL
 INTEGER::NBASE,NV2,NORBIT
 IBLOCK=BLOCK_TOTAL(LUSE)
 NORBIT=STATE_TOTAL(LUSE,NSHELL)
 NBASE =   MS_TOTAL(LUSE,NSHELL)
 NV2   =   V2_TOTAL(LUSE,NSHELL)
! write(*,*)nbase,nv2,IBLOCK;stop
!ALLOCATE RHOS
 IF(.NOT.(ALLOCATED(RHO_UU)))    ALLOCATE(RHO_UU(0:NMAX,0:NMAX,0:IBLOCK))
 IF(.NOT.(ALLOCATED(RHONEW_UU))) ALLOCATE(RHONEW_UU(0:NMAX,0:NMAX,0:IBLOCK))
 IF(.NOT.(ALLOCATED(B_LABEL)))   ALLOCATE(B_LABEL(0:IBLOCK))
 IF(.NOT.(ALLOCATED(B_DEGE)))    ALLOCATE(B_DEGE(0:NMAX,0:IBLOCK))
!ALLOCATE EIGENS
 IF(.NOT.(ALLOCATED(EVEC_UU)))   ALLOCATE(EVEC_UU(0:NMAX,0:NMAX,0:IBLOCK))
 IF(.NOT.(ALLOCATED(EIGVAL)))    ALLOCATE(EIGVAL(0:NMAX,0:IBLOCK))
 IF(.NOT.(ALLOCATED(EIGVAL_NEW)))ALLOCATE(EIGVAL_NEW(0:NMAX,0:IBLOCK))
 IF(.NOT.(ALLOCATED(EIGORD)))    ALLOCATE(EIGORD(0:NORBIT))
!ALLOCATE VTABLES
 IF(.NOT.(ALLOCATED(VMTAB)))     ALLOCATE(VMTAB(1:NBASE,1:NBASE,1:NBASE,1:NBASE))
 IF(.NOT.(ALLOCATED(MLABEL)))    ALLOCATE(MLABEL(0:NMAX,0:LMAX,1:JMAX,-JMAX:JMAX,0:TMAX))
!ALLOCATE <A|V|B> 
 IF(.NOT.(ALLOCATED(V2B_UU)))    ALLOCATE(V2B_UU(1:NV2,1:NV2))
 IF(.NOT.(ALLOCATED(JLABEL)))    ALLOCATE(JLABEL(1:NV2))
 IF(.NOT.(ALLOCATED(JORB)))      ALLOCATE(JORB(0:NMAX,0:NMAX,0:LMAX,0:NSPIN))
!ALLOCATE <I|V|J>
 IF(.NOT.(ALLOCATED(TUMAT)))     ALLOCATE(TUMAT(0:NMAX,0:NMAX,0:LMAX))

 IF(.NOT.(ALLOCATED(VTEMP)))     ALLOCATE(VTEMP(0:NMAX,0:NMAX,0:NMAX,0:NMAX))
 IF(.NOT.(ALLOCATED(TTEMP)))     ALLOCATE(TTEMP(0:NMAX,0:NMAX))

 IF(.NOT.(ALLOCATED(HMAT_UU)))   ALLOCATE(HMAT_UU(0:NMAX,0:NMAX))
 IF(.NOT.(ALLOCATED(VMEAN_UU)))  ALLOCATE(VMEAN_UU(0:NMAX,0:NMAX))

 RETURN
END SUBROUTINE LOADS

SUBROUTINE DELOADS
USE PARS
USE BLOCKS
USE RHOS
USE EIGENS
USE EORDER
USE RESHAPED
USE TABLES
USE TUMATS
USE V2MATS
USE VMEANS
USE HMATS
IMPLICIT NONE
!
 DEALLOCATE(RHO_UU,RHONEW_UU,B_LABEL,B_DEGE)
 DEALLOCATE(EVEC_UU,EIGVAL,EIGVAL_NEW,EIGORD)
 DEALLOCATE(VMTAB,MLABEL)
 DEALLOCATE(V2B_UU,JLABEL,JORB)
 DEALLOCATE(TUMAT)
 DEALLOCATE(VTEMP,TTEMP)
 DEALLOCATE(HMAT_UU,VMEAN_UU)

 RETURN
END SUBROUTINE DELOADS

SUBROUTINE BLOCK_LABEL!change quantum number of blocks into standard 1d label
USE BLOCKS
USE PARS
IMPLICIT NONE
 INTEGER::NL,L,S,START,I
 INTEGER::SSTART,NLIMIT
 B_LABEL(:)%NL=0;B_LABEL(:)%L=0
 B_LABEL(:)%S=0;B_LABEL(:)%OCC=0
 B_DEGE(:,:)=0
 I=0
 DO L=0,LUSE
    START=SSTART(L)
    NL=NLIMIT(L,NSHELL)
    DO S=NSPIN,START,-1
!    do s=start,nspin
       B_LABEL(I)%NL=NL;B_LABEL(I)%L=L;B_LABEL(I)%S=S
       I=I+1
    ENDDO
 ENDDO
 RETURN
END SUBROUTINE BLOCK_LABEL

SUBROUTINE INITIAL_RHO(TFIX)
USE RHOS
USE EIGENS
USE BLOCKS
IMPLICIT NONE
 INTEGER::TFIX
 INTEGER::I,N,NL,JM,NREMAIN
 INTEGER::MAX_DEGE
 RHO_UU(:,:,:)=0.0D0;RHONEW_UU(:,:,:)=0.0D0
 EIGVAL_NEW(:,:)=0.0D0;EIGVAL(:,:)=0.0D0
 NREMAIN=TFIX
 DO I=0,IBLOCK
    NL=B_LABEL(I)%NL
    DO N=0,NL
       JM=MAX_DEGE(N,I)
       NREMAIN=NREMAIN-JM
       IF(NREMAIN>0)THEN
          RHO_UU(N,N,I)=JM
          B_DEGE(N,I)=JM
       ELSE
          RHO_UU(N,N,I)=NREMAIN+JM
          B_DEGE(N,I)=NREMAIN+JM
          GO TO 1
       ENDIF
    ENDDO
 ENDDO

   1 CONTINUE
END SUBROUTINE INITIAL_RHO

SUBROUTINE INITIAL(TFIX)
USE PARS

USE BLOCKS
IMPLICIT NONE
 INTEGER:: TFIX
!
 CALL LOADS!LOAD SPACES
 CALL BLOCK_LABEL!BUILD BLOCK LABELS
! 
 CALL T1BODY !CALCULATE ONE-BODY MATRIX ELEMENTS
 CALL V2_BUILD!CALCULATE TWO-BODY MATRIX ELEMENTS
 CALL INITIAL_RHO(TFIX)!INITIALIZE RHO MATRIX
!
 RETURN
END SUBROUTINE INITIAL

