!===========================================
!DIAGONALIZE H MATRIX IN BLOCK A          ==
!===========================================
SUBROUTINE DIAG_MAT(N,H,EVAL)!diagonalize input matrx
USE PARS
IMPLICIT NONE
!IN&OUT PUTS
 INTEGER ::N
 REAL(DP)::H(0:N,0:N),EVAL(0:N)
!VARIABLES FOR DIAGONALIZATION
 INTEGER::LWORK,NB,INFO
 REAL(DP),ALLOCATABLE::WORK(:)
 CHARACTER::JOBZ,UPLO
!
 JOBZ='V';UPLO='U'

 IF(.NOT.ALLOCATED(WORK))THEN
    CALL DSYEV(JOBZ,UPLO,NMAX+1,H(0:NMAX,0:NMAX),NMAX+1,&
               EVAL(0:NMAX),EVAL(0:NMAX),-1,INFO)
    LWORK=EVAL(0)
    ALLOCATE(WORK(LWORK))
 ENDIF
!DIAGONALIZATION
 CALL DSYEV(JOBZ,UPLO,N+1,H(0:N,0:N),N+1,&
             EVAL(0:N),WORK,LWORK,INFO)
! stop
 RETURN
END SUBROUTINE DIAG_MAT

SUBROUTINE HDIAG_A(NL,A)!DIAGONALIZE THE LTH BLOCK IN FULL H  
USE PARS
USE HMATS
USE EIGENS
IMPLICIT NONE
 INTEGER::NL,A
 INTEGER::S,START,SSTART
 REAL(DP)::HTEMP(0:NMAX,0:NMAX),ETEMP(0:NMAX)
!
 HTEMP(:,:)=0.0D0;ETEMP(:)=0.0D0
    HTEMP(0:NL,0:NL)=HMAT_UU(0:NL,0:NL)
    CALL DIAG_MAT(NL,HTEMP(0:NL,0:NL),ETEMP(0:NL))
    EIGVAL_NEW(0:NL,A)=ETEMP(0:NL)
    EVEC_UU(0:NL,0:NL,A)=HTEMP(0:NL,0:NL)   
 RETURN
END SUBROUTINE HDIAG_A
!===========================================
!DETERMINE PARTICLE NUMBER IN EACH ORBIT  ==
!===========================================
SUBROUTINE E_REORDER(NFIX)
USE PARS
USE EIGENS
USE BLOCKS
USE EORDER
IMPLICIT NONE
 
 INTEGER::NFIX
 INTEGER::ITOTAL,I,J
 INTEGER::N,NL,IBEGIN,IEND,A,JM,NREMAIN
 INTEGER::STATE_TOTAL,MAX_DEGE
 TYPE(EINDX)::ETEMP
!
 ITOTAL=STATE_TOTAL(LUSE,NSHELL)
 EIGORD(:)%E=0.0D0;EIGORD(:)%N=0;EIGORD(:)%A=0    
!write(*,*)iblock;stop
 IBEGIN=0;IEND=0;
!
 DO A=0,IBLOCK!MERGE EIGEN VALUE IN EVERY BLOCK
    NL=B_LABEL(A)%NL
    DO N=0,NL    
       EIGORD(IBEGIN+N)%E=EIGVAL_NEW(N,A)
!       WRITE(*,*)EIGVAL_NEW(N,A),N,A
       EIGORD(IBEGIN+N)%N=N;EIGORD(IBEGIN+N)%A=A
    ENDDO
    IBEGIN=IBEGIN+NL+1
 ENDDO
!
 DO I=0,ITOTAL-1!ARRANGE ENERGIES IN ASCENDING ORDER
    DO J=I+1,ITOTAL
       IF (EIGORD(J)%E<EIGORD(I)%E)THEN
          ETEMP=EIGORD(I);EIGORD(I)=EIGORD(J);EIGORD(J)=ETEMP
       ENDIF
    ENDDO
 ENDDO
!
 B_DEGE(:,:)=0;B_LABEL(:)%OCC=0!CLEAN THE OCCUPATION NUMBERS IN LAST ITERATION
 I=0;NREMAIN=NFIX
 DO WHILE(NREMAIN>0)!FIND OCCUPIED 2j+1 FOLDED HF STATE IN EACH BLOCK AND PARTICLE NUBMER IN EACH STATE
    JM=MAX_DEGE(EIGORD(I)%N,EIGORD(I)%A)!
    NREMAIN=NREMAIN-JM
    IF(NREMAIN>0)THEN
       B_DEGE(EIGORD(I)%N,EIGORD(I)%A)=JM!PUT 2J+1 PARTICLE INTO CURRENT HF STATE
       B_LABEL(EIGORD(I)%A)%OCC=B_LABEL(EIGORD(I)%A)%OCC+1
!       write(*,*)eigord(I)%E,eigord(I)%n,b_label(eigord(I)%A)%l,b_label(eigord(I)%A)%s,B_DEGE(EIGORD(I)%N,EIGORD(I)%A)
    ELSE!LAST ORBIT MAY NOT BE FULLY OCCUPIED
       B_DEGE(EIGORD(I)%N,EIGORD(I)%A)=NREMAIN+JM!PUT REMAIN PARTICLE INTO CURRENT HF STATE
       B_LABEL(EIGORD(I)%A)%OCC=B_LABEL(EIGORD(I)%A)%OCC+1
!       write(*,*)eigord(I)%E,eigord(I)%n,b_label(eigord(I)%A)%l,b_label(eigord(I)%A)%s,B_DEGE(EIGORD(I)%N,EIGORD(I)%A)
    ENDIF 
    I=I+1!MOVE TO NEXT ORBIT  
 ENDDO
 RETURN
END SUBROUTINE E_REORDER
!===========================================
!FIND G.S ENERGY                          ==
!===========================================
SUBROUTINE ENERGY_A(NL,N_OCC,DEG,EVNEW,EV,ENLS,ERRLS)!FIND SPE IN A BLOCK AND UPDATE EIGVAL
USE PARS
IMPLICIT NONE
 INTEGER ::NL,N_OCC
 REAL(DP)::EVNEW(0:NMAX),EV(0:NMAX)
 INTEGER ::DEG(0:NMAX)
 REAL(DP)::ENLS,ERRLS
 INTEGER::ISPIN,I
 ENLS=0.0D0;ERRLS=0.0D0
 DO I=0,NL
    IF(I<=N_OCC)ENLS=ENLS+EVNEW(I)*DEG(I)
    ERRLS=ERRLS+ABS(EVNEW(I)-EV(I))
 ENDDO
 EV(:)=EVNEW(:)
 RETURN
END SUBROUTINE ENERGY_A

SUBROUTINE TE_A(NL,A,TUES)!TR((T+U)*RHO) IN A BLOCK
USE PARS
USE RESHAPED
USE RHOS
!USE EIGENS
IMPLICIT NONE
 INTEGER::NL,A
 REAL(DP)::TUES,SUMS
 INTEGER::I,JM
 SUMS=0.0D0
 !CALL RESHAPE!!!!!!!!!!!!!!!!
 CALL T1_RESHAPE(A)
 DO I=0,NL
    SUMS=SUMS+TTEMP(I,I)*RHO_UU(I,I,A)
 ENDDO
 TUES=SUMS
END SUBROUTINE TE_A

SUBROUTINE TE_ALL(TENERGY)!TOTAL T ENERGY
USE PARS
USE BLOCKS
IMPLICIT NONE
 REAL(DP)::TENERGY
 INTEGER ::I,NL
 REAL(DP)::TUES
 TENERGY=0.0D0
 DO I=0,IBLOCK
    NL=B_LABEL(I)%NL
    CALL TE_A(NL,I,TUES)
    TENERGY=TENERGY+TUES
 ENDDO
 RETURN 
END SUBROUTINE TE_ALL

SUBROUTINE ENERGY_NEW(EGS,ERROR)!FIND G.S ENERGY;CALCULATE ERRORS;UPDATE EIGVALUE VECTOR
USE PARS
USE EIGENS
USE BLOCKS
IMPLICIT NONE
 REAL(DP)::EGS,ERROR
 INTEGER ::I,NL,NEIG,N_OCC,NLIMIT,SSTART
 REAL(DP)::TENERGY,ENI,ERRI
 EGS=0.0D0;ERROR=0.0D0;NEIG=0
!
 DO I=0,IBLOCK
    N_OCC=B_LABEL(I)%OCC
    NL=B_LABEL(I)%NL
    CALL ENERGY_A(NL,N_OCC,B_DEGE(:,I),EIGVAL_NEW(:,I),&
         EIGVAL(:,I),ENI,ERRI)
    EGS=EGS+ENI;ERROR=ERROR+ERRI;NEIG=NEIG+(NL+1)
 ENDDO
!ONE BODY ENERGY
 CALL TE_ALL(TENERGY)
!
 EGS=0.5*(EGS+TENERGY)
 ERROR=ERROR/NEIG
 RETURN
END SUBROUTINE ENERGY_NEW 

!===========================================
!SOLVE HF BY ITERATION                    ==
!===========================================
SUBROUTINE ITERS(NFIX,EPSI,ITMAX,ITNOW,IFLAG,FLAGMAX,RMIX,EGS)
USE PARS
USE RHOS
USE TUMATS
USE EIGENS
USE BLOCKS
IMPLICIT NONE
 REAL(DP)::EPSI,RMIX,ERROR
 INTEGER ::NFIX,ISPINC,ITMAX,ITNOW,IFLAG,FLAGMAX
 REAL(DP)::EGS,TES
 INTEGER ::A,NL
!
100 FORMAT(A4,5X,A9,3X,A10)
!200 FORMAT(I4,5X,F9.5,3X,E10.3)
200 FORMAT(I4,5X,F9.5,3X,E10.3,E12.5,E12.5)
 WRITE(*,100)'ITER','ENERGY','DIFF'
 DO WHILE ((IFLAG<FLAGMAX).AND.(ITNOW<=ITMAX))
!
    DO A=0,IBLOCK!DIAGONAL EVERY L BLOCK
       NL=B_LABEL(A)%NL
       CALL HMAT_A (A)!BUILD H MATRIX      
       CALL HDIAG_A(NL,A)!DIAGONALIZATION        
    ENDDO!END DIAGONALIZE IN ALL BLOCKS
!
    CALL E_REORDER(NFIX)!FIND ASCENDING ORDER
    CALL RHO_ALL!RHO IS BUILD AFTER ORDERING ENERGY IN DIFFERENT BLOCK
    CALL ENERGY_NEW(EGS,ERROR)
    CALL RHO_NEW(RMIX)   
!
    WRITE(*,200)ITNOW,EGS,ERROR,EIGVAL(0,0),EIGVAL(1,0)
    IF(ABS(ERROR)<EPSI) IFLAG=IFLAG+1
    ITNOW=ITNOW+1
 ENDDO
 RETURN
END SUBROUTINE ITERS
