SUBROUTINE T1BODY
USE PARS
USE TUMATS
IMPLICIT NONE
 INTEGER::L,N,NLIMIT
 INTEGER::I,NN
 REAL(DP)::FACTOR
 FACTOR=HBROMG
 TUMAT(:,:,:)=0.0D0
 DO L=0,LUSE
    NN=NLIMIT(L,NSHELL)
    DO N=0,NN
       TUMAT(N,N,L)=FACTOR*(2*N+L+1.5D0)
    ENDDO
 ENDDO
 RETURN
END SUBROUTINE T1BODY
