!===========================================
!CHANGE T AND V MATRIX INTO STANDARD SHAPE==
!===========================================
SUBROUTINE T1_RESHAPE(I)!PUT <NLS|T|NLS> INTO <N|T|N>(I)
USE PARS
USE TUMATS
USE RESHAPED
USE BLOCKS
IMPLICIT NONE
 INTEGER ::I
 INTEGER ::L
 TTEMP(:,:)=0.0D0
 L=B_LABEL(I)%L
 TTEMP(:,:)=TUMAT(:,:,L)
 RETURN
END SUBROUTINE T1_RESHAPE

SUBROUTINE V2_RESHAPE(I,J)!PUT <A|v|B>(I,J LABEL FIXED) INTO V(N1,N2,N3,N4)
USE PARS
USE V2MATS
USE BLOCKS
USE RESHAPED
IMPLICIT NONE
 INTEGER ::I,J
 INTEGER ::L,S,LP,SP
 INTEGER ::NLIMIT
 INTEGER ::NL,NLP,N1,N2,N3,N4,A,B
 VTEMP(:,:,:,:)=0.0D0
!FIND L,J,L',JP' LABEL
  NL=B_LABEL(I)%NL; L=B_LABEL(I)%L; S=B_LABEL(I)%S
 NLP=B_LABEL(J)%NL;LP=B_LABEL(J)%L;SP=B_LABEL(J)%S
!
 DO N1=0,NL
   DO N2=0,NLP
      DO N3=0,NL
         DO N4=0,NLP
if(i==j)then
           A=JORB(N1,N3,L,S);B=JORB(N2,N4,LP,SP)
           VTEMP(N1,N2,N3,N4)=V2B_UU(A,B)
!if(n1<=2.and.n2<=2.and.n3<=2.and.n4<=2)then
! vtemp(n1,n2,n3,n4)=0.0d0
 endif
         ENDDO
      ENDDO
   ENDDO
ENDDO
RETURN
END SUBROUTINE V2_RESHAPE
!===========================================
!CALCULATE RHO MATRIX                     ==
!===========================================
SUBROUTINE RHO_BASIC(NL,N_OCC,DEG,VEC1,VEC2,RHOMAT)!RHO=D(')*D
USE PARS
IMPLICIT NONE
 INTEGER::NL,N_OCC
 REAL(DP)::VEC1(0:NMAX,0:NMAX),VEC2(0:NMAX,0:NMAX)!EIGEN VECTOR
 INTEGER::DEG(0:NMAX)!PARTICLE NUMBER IN EACH OCCUPIED ORBIT
 REAL(DP)::RHOMAT(0:NMAX,0:NMAX)!OUTPUT RHO
 INTEGER::IBRA,IKET,I
 REAL(DP)::SUMS
 RHOMAT(:,:)=0.0D0
 DO IBRA=0,NL
    DO IKET=0,NL
       SUMS=0.0D0
       DO I=0,N_OCC-1!FROM 0 TO N_OCC-1, TOTAL NUMBER IS N_OCC
             SUMS=SUMS+VEC1(IBRA,I)*VEC2(IKET,I)*DEG(I)
       ENDDO
       RHOMAT(IBRA,IKET)=SUMS
    ENDDO
 ENDDO
 RETURN
END SUBROUTINE RHO_BASIC 

SUBROUTINE RHO_A(A)!RHO IN BLOCK A
USE PARS
USE EIGENS
USE RHOS
USE BLOCKS
IMPLICIT NONE 
 INTEGER :: A
 REAL(DP)::RMIX
 INTEGER :: NL,N_OCC
 REAL(DP):: RTEMP(0:NMAX,0:NMAX)
 INTEGER:: DEG(0:NMAX)
 NL=B_LABEL(A)%NL
 N_OCC=B_LABEL(A)%OCC!FIND THE NUMBER OF OCCUPIED ORBIT IN THIS L,J BLOCK
 DEG=B_DEGE(:,A)!PARTICLE NUMBER IN EACH OCCUPIED ORBIT
 CALL RHO_BASIC(NL,N_OCC,DEG,EVEC_UU(:,:,A),&
      EVEC_UU(:,:,A),RHONEW_UU(:,:,A))
 RETURN
END SUBROUTINE RHO_A

SUBROUTINE RHO_ALL!BUILD NEW RHO MATRIX
USE PARS
USE BLOCKS
IMPLICIT NONE
 INTEGER::A
 DO A=0,IBLOCK
    CALL RHO_A(A)
 ENDDO
END SUBROUTINE RHO_ALL

SUBROUTINE RHO_NEW(RMIX)!MIX RHO MATRIX WITH OLD ONE
USE RHOS
IMPLICIT NONE
 REAL(DP)::RMIX
 INTEGER::SMAX,ISPIND
 RHO_UU(:,:,:)=RHONEW_UU(:,:,:)*RMIX&
                +RHO_UU(:,:,:)*(1-RMIX)       
 RETURN
END SUBROUTINE RHO_NEW
!===========================================
!BUILD V_MEAN IN BLOCK A FROM V2 AND RHO  ==
!===========================================
SUBROUTINE VMEAN_BASIC(NL,NLP,VMAT,RHOMAT,VMAT_MEAN)!V(N1,N2,N3,N4)*RHO(N2,N4)
USE PARS
IMPLICIT NONE
 INTEGER::NL,NLP
 REAL(DP)::VMAT(0:NMAX,0:NMAX,0:NMAX,0:NMAX),RHOMAT(0:NMAX,0:NMAX)
 REAL(DP)::VMAT_MEAN(0:NMAX,0:NMAX)
 INTEGER::N1,N2,N3,N4
 REAL(DP)::SUMS
 VMAT_MEAN(:,:)=0.0D0
 DO N1=0,NL
    DO N3=0,NL
       SUMS=0.0D0
       DO N2=0,NLP
          DO N4=0,NLP
             SUMS=SUMS+VMAT(N1,N2,N3,N4)*RHOMAT(N4,N2)
          ENDDO
       ENDDO
       VMAT_MEAN(N1,N3)=SUMS
    ENDDO
 ENDDO
 RETURN
END SUBROUTINE VMEAN_BASIC

SUBROUTINE VMEAN_A(A)!VMEAN(A)=V(A,B)*RHO(B),SUMS OVER B
USE PARS
USE VMEANS
USE RHOS
USE BLOCKS
USE RESHAPED
IMPLICIT NONE
 INTEGER :: A
 REAL(DP):: VM_TEMP(0:NMAX,0:NMAX)
 INTEGER :: B,NL,NLP
!
 VMEAN_UU(:,:)=0.0D0
 NL=B_LABEL(A)%NL
 DO B=0,IBLOCK
     NLP=B_LABEL(B)%NL
    CALL V2_RESHAPE(A,B)
    CALL VMEAN_BASIC(NL,NLP,VTEMP,RHO_UU(:,:,B),VM_TEMP)
    VMEAN_UU(0:NL,0:NL)=VMEAN_UU(0:NL,0:NL)+VM_TEMP(0:NL,0:NL)
!    if(a==0.and.b==0)then
!     write(*,*)vmean_uu(0:nl,0:nl),nl,b_label(b)%l,b_label(b)%s
!    endif
 ENDDO
! WRITE(*,*)VMEAN_UU(0:nl,0:nl),b_label(a)%l,b_label(a)%s
 RETURN
END SUBROUTINE VMEAN_A 

!===========================================
!BUILD H IN BLOCK A                       ==
!===========================================

SUBROUTINE HMAT_A(A)!BUILD H MATRIX WITH FIXED A
USE TUMATS
USE VMEANS
USE HMATS
USE PARS
USE RESHAPED
use blocks
IMPLICIT NONE
 INTEGER::A
 HMAT_UU(:,:)=0.0D0
 CALL VMEAN_A(A)
 CALL T1_RESHAPE(A)
 HMAT_UU(:,:)=TTEMP(:,:)+VMEAN_UU(:,:)!TU MAT IS DIAGONAL IN AND INDEPENDENT FROM SPIN
!WRITE(*,*)vmean_UU(0:b_label(a)%nl,0:b_label(a)%nl),b_label(a)%l,b_label(a)%s 
! hmat_uu(:,:)=ttemp(:,:)
!stop
 RETURN
END SUBROUTINE HMAT_A 

