SUBROUTINE V2MFILE(NAMA,NAMA2)!READ .DAT FILE AND STORE V(A,B,C,D)
USE PARS
USE TABLES
IMPLICIT NONE
 CHARACTER(LEN=*)::NAMA,NAMA2
 INTEGER::IORBIT
 INTEGER::IFLAG,A,B,C,D,E,ORB!,NR
 CHARACTER(LEN=5)::TEMP1
 CHARACTER(LEN=7)::TEMP2
 REAL(DP)::V
 IFLAG=0
 VMTAB(:,:,:,:)=0.0D0
 MLABEL(:,:,:,:,:)=0
 OPEN(10,FILE=NAMA)
 DO WHILE(IFLAG==0)
    READ(10,FMT=*,IOSTAT=IFLAG)A,B,C,D,V 
    IF(IFLAG==0)THEN
       VMTAB(A,B,C,D)=V
    ENDIF  
 ENDDO
 CLOSE(10)
!
100 FORMAT(13X, I3,2X,  5(1X,I3))
 IFLAG=0!;NR=1
 OPEN(10,FILE=NAMA2)
 DO WHILE(IFLAG==0)
    READ(10,FMT=100,IOSTAT=IFLAG)ORB,A,B,C,D,E
    IF(IFLAG==0)THEN
       IF(E==-1) E=0
       MLABEL(A,B,C,D,E)=ORB
    ENDIF
 ENDDO
 CLOSE(10)
!
 RETURN
END SUBROUTINE V2MFILE

SUBROUTINE V2MMAT_NLJ(N1,N2,N3,N4,L,J,LP,JP,RES)!<N1LJ,N2L'J'|V|N3LJ,N4L'J'>
USE PARS
USE TABLES
IMPLICIT NONE
 INTEGER ::N1,N2,N3,N4,L,J,LP,JP
 INTEGER ::M,MP,I1,I2,I3,I4,T
 REAL(DP)::RES
 T=1;RES=0.0D0
 DO M=-J,J,2
    DO MP=-JP,JP,2
       I1=MLABEL(N1,L,J,M,T);   I3=MLABEL(N3,L,J,M,T)
       I2=MLABEL(N2,LP,JP,MP,T);I4=MLABEL(N4,LP,JP,MP,T)
       RES=RES+VMTAB(I1,I2,I3,I4)!-vmtab(i1,i2,i4,i3)
    ENDDO
 ENDDO
!
 RES=RES/((J+1)*(JP+1))
 RETURN
END SUBROUTINE V2MMAT_NLJ

SUBROUTINE INDEX_BUILD(IORB)!N1,N3,L,J <-> A, TOTAL A NUMBER
USE V2MATS
IMPLICIT NONE
 INTEGER::IORB
 INTEGER::N1,N3,L,J
 INTEGER::NLIMIT,SSTART
 INTEGER::I,NN,S,START
 I=0
 DO L=0,LUSE
    START=SSTART(L)
    DO S=START,NSPIN
       NN=NLIMIT(L,NSHELL)
       J=2*(L+S)-1!2J VALUE
       DO N1=0,NN
          DO N3=0,NN
             I=I+1
             JLABEL(I)%N1=N1;JLABEL(I)%N3=N3;JLABEL(I)%L=L;JLABEL(I)%J=J;
             JORB(N1,N3,L,S)=I
          ENDDO
       ENDDO
    ENDDO
 ENDDO
 IORB=I!TOTAL STATES NUMBER
 RETURN
END SUBROUTINE INDEX_BUILD

SUBROUTINE VMAT_AB(IORB)!BUILD AVERAGE V MATRIX
USE PARS
USE V2MATS
IMPLICIT NONE
 INTEGER::IORB
 INTEGER::A,B,L,J,LP,JP,N1,N2,N3,N4
 REAL(DP)::RES
 V2B_UU(:,:)=0.0D0
 DO A=1,IORB
    DO B=1,IORB
        L=JLABEL(A)%L; J=JLABEL(A)%J;N1=JLABEL(A)%N1;N3=JLABEL(A)%N3
       LP=JLABEL(B)%L;JP=JLABEL(B)%J;N2=JLABEL(B)%N1;N4=JLABEL(B)%N3
       CALL V2MMAT_NLJ(N1,N2,N3,N4,L,J,LP,JP,RES)
       V2B_UU(A,B)=RES
    ENDDO
 ENDDO
 RETURN
END SUBROUTINE VMAT_AB

SUBROUTINE V2_BUILD
IMPLICIT NONE
 CHARACTER(LEN=30)::NAMA,NAMA2
 INTEGER::IORB
 NAMA='VM-scheme.dat';NAMA2='spM.dat'
 CALL V2MFILE(TRIM(NAMA),TRIM(NAMA2))!READ V2 TABLE FROM FILE
 CALL INDEX_BUILD(IORB)  !BUILD INDEX
 CALL VMAT_AB(IORB)      !BUILD AVERAGE V2 MATRIX
 RETURN
END SUBROUTINE
