MODULE PARS
 INTEGER,PARAMETER::DP=8
 INTEGER,PARAMETER::NMAX=50
 INTEGER,PARAMETER::LMAX=0
 INTEGER,PARAMETER::GMAX=150
 INTEGER::NUSE,LUSE,GUSEX,GUSEY
 REAL(DP)::BOSC,HBAR2M,HBROMG!OSCILLATOR LENGTH^(-1)
 REAL(DP)::KAPPAR,KAPPAS,V0R,V0S!COEFFICIENT OF THE POTENTIAL 
 CHARACTER(LEN=100)::QUAD
END MODULE PARS

MODULE GAUSS
USE PARS
REAL(DP)::WX(1:GMAX),WY(1:GMAX)
REAL(DP)::XMESH(1:GMAX),YMESH(1:GMAX)
END MODULE GAUSS

MODULE LOGS
USE PARS
REAL(DP)::LOGANL(0:NMAX,0:LMAX)
END MODULE LOGS

!MODULE LX2D!L POLYNORMIAL AT DIFFERENT MESH POINTS; MESH POINTS
!USE PARS
!REAL(DP)::X2D1(1:GMAX,1:GMAX),X2D2(1:GMAX,1:GMAX)
!REAL(DP)::X2D3(1:GMAX,1:GMAX),X2D4(1:GMAX,1:GMAX)
!REAL(DP)::L2D1(0:NMAX,0:LMAX,1:GMAX,1:GMAX),L2D2(0:NMAX,0:LMAX,1:GMAX,1:GMAX)
!REAL(DP)::L2D3(0:NMAX,0:LMAX,1:GMAX,1:GMAX),L2D4(0:NMAX,0:LMAX,1:GMAX,1:GMAX)
!END MODULE LX2D

MODULE LX1D!L POLYNORMIAL AT DIFFERENT MESH POINTS; MESH POINTS
USE PARS
REAL(DP)::X1D(1:GMAX)
REAL(DP)::L1D(0:NMAX,0:LMAX,1:GMAX)
END MODULE LX1D

MODULE HRHOMAT
USE PARS
REAL(DP)::HMAT(0:NMAX,0:NMAX)
REAL(DP)::RHOS(0:NMAX,0:NMAX)
!REAL(DP)::RHOS_OLD(0:NMAX,0:NMAX)
END MODULE HRHOMAT

MODULE TVUMAT
USE PARS
!REAL(DP)::TMAT(0:NMAX,0:NMAX)
!REAL(DP)::UMAT(0:NMAX,0:NMAX)
REAL(DP)::TUMAT(0:NMAX,0:NMAX)
REAL(DP)::VMAT(0:NMAX,0:NMAX,0:NMAX,0:NMAX)
REAL(DP)::V1MAT(0:NMAX,0:NMAX)
END MODULE TVUMAT

MODULE EIGENS
USE PARS
REAL(DP)::EIGVAL(0:NMAX)
REAL(DP)::EIGVAL_OLD(0:NMAX)
REAL(DP)::EIGVEC(0:NMAX,0:NMAX)
INTEGER::EIGORD(0:NMAX)
END MODULE EIGENS

