FUNCTION FX(X1,X2,A) RESULT(RES)
USE PARS
IMPLICIT NONE
 REAL(DP)::X1,X2,A,SQRS,RES
 SQRS=A*SQRT(X1*X2)
 RES=EXP(SQRS)-EXP(-SQRS)
! RES=SQRT(X1*X2)
!  RES=1.0d0
 RETURN
END FUNCTION FX

SUBROUTINE V2MATRX(L,KAPPA,VFACTOR,VINMAT)!(ab|VD,E|cd)
USE PARS
USE GAUSS
USE LX1D
USE LOGS
IMPLICIT NONE
 INTEGER::L
 REAL(DP)::FX,KAPPA,VFACTOR
 REAL(DP)::VINMAT(0:NMAX,0:NMAX,0:NMAX,0:NMAX)
 REAL(DP)::VDMAT(0:NMAX,0:NMAX,0:NMAX,0:NMAX)
 REAL(DP)::VEMAT(0:NMAX,0:NMAX,0:NMAX,0:NMAX)
 REAL(DP)::ALPHA,FAC1,FAC2,FACTOR,SUMS,TEMPS
 INTEGER::I,J,A,B,C,D
 ALPHA=0.0D0
 VINMAT(:,:,:,:)=0.0D0;VDMAT(:,:,:,:)=0.0D0;VEMAT(:,:,:,:)=0.0D0
 FAC1=KAPPA+1.0D0;FAC2=2*KAPPA/FAC1

 X1D(:)=XMESH(:)/FAC1
 CALL LNL1D(X1D,L1D)!CALCULATE LAGUERRE POLYNOMIAL
!CONSTRUCT V MATRIX
 DO A=0,NUSE 
   DO B=0,NUSE
     DO C=0,NUSE
       DO D=0,NUSE
         SUMS=0.0D0
         FACTOR=EXP(LOGANL(A,L)+LOGANL(B,L)+LOGANL(C,L)+LOGANL(D,L))!*0.25D0
         DO I=1,GUSEX
           DO J=1,GUSEX
             SUMS=SUMS+WX(I)*WX(J)*L1D(A,L,I)*L1D(B,L,J)&
                                  *L1D(C,L,I)*L1D(D,L,J)&
                                  *FX(XMESH(I),XMESH(J),FAC2)
           ENDDO
         ENDDO
         VDMAT(A,B,C,D)=SUMS*FACTOR
         VEMAT(A,B,D,C)=SUMS*FACTOR
       ENDDO
     ENDDO
   ENDDO
 ENDDO
 FACTOR=VFACTOR/(16.0D0*KAPPA*(KAPPA+1)**2)
 VINMAT(:,:,:,:)=(VDMAT(:,:,:,:)+VEMAT(:,:,:,:))*FACTOR                  
 RETURN
END SUBROUTINE V2MATRX

SUBROUTINE V2TOTAL(L)
USE PARS
USE TVUMAT
IMPLICIT NONE
 REAL(DP)::VR(0:NMAX,0:NMAX,0:NMAX,0:NMAX)
 REAL(DP)::VS(0:NMAX,0:NMAX,0:NMAX,0:NMAX)
 INTEGER::L
 REAL(DP)::KR_PRIME,KS_PRIME,ALPHA,VUNIT
 VR(:,:,:,:)=0.0D0;VS(:,:,:,:)=0.0D0
!
 KR_PRIME=KAPPAR/BOSC**2;KS_PRIME=KAPPAS/BOSC**2
 VUNIT=1.0D0
 CALL V2MATRX(L,KR_PRIME,VUNIT,VR)
 CALL V2MATRX(L,KS_PRIME,VUNIT,VS)
 VMAT(:,:,:,:)=(V0R*VR(:,:,:,:)+V0S*VS(:,:,:,:))*0.5D0
 RETURN
END SUBROUTINE V2TOTAL
