SUBROUTINE V2TEST(L,RSURF,VFACTOR)!FIX V MATRIX ELEMENTS FOR TESTING
USE PARS
USE LOGS
USE TVUMAT
IMPLICIT NONE
 INTEGER::L
 REAL(DP)::VFACTOR,RSURF,ALPHA,XI2,FACTOR,SUMS
 REAL(DP)::LTEMP(0:NMAX)
 INTEGER::I,J,A,B,C,D
 
 VMAT(:,:,:,:)=0.0D0
 ALPHA=L+0.5D0
 XI2=(BOSC*RSURF)**2
 CALL ANLS
 CALL laguerre_general(NUSE, alpha, XI2, LTEMP(0:NUSE))
!
 DO A=0,NUSE 
   DO B=0,NUSE
     DO C=0,NUSE
       DO D=0,NUSE
         IF(A<3 .AND. B<3 .AND. C<3 .AND.D<3)THEN
         VMAT(A,B,C,D)=VFACTOR
         ENDIF
       ENDDO
     ENDDO
   ENDDO
 ENDDO               
 RETURN
END SUBROUTINE V2TEST
