SUBROUTINE ANLS!log(Anl) at each n,l point,B^1.5 factor is not included
USE PARS
USE LOGS
IMPLICIT NONE
 INTEGER::n,L
 LOGANL(:,:)=0.0D0   
 DO n=0,NUSE
    DO L=0,LUSE
       LOGANL(n,L)=0.5D0*LOG(2.0D0)&
                  +0.5D0*(LOG_GAMMA(REAL(n+1,kind=DP))&
                  -LOG_GAMMA(REAL(n+l+1.5,kind=DP)))
    ENDDO
 ENDDO
 RETURN
END SUBROUTINE ANLS

SUBROUTINE XLNL1D!1D Mesh points -> Variable values
USE PARS
USE GAUSS
USE LX1D
IMPLICIT NONE
 INTEGER::I
 X1D(:)=XMESH(:)
 RETURN
END SUBROUTINE XLNL1D

SUBROUTINE LNL1D(X2,LPOLY)! CONSTRUCT L_{nl}^{alpha} at each l, n, x2(I) point
USE PARS
IMPLICIT NONE
 REAL(dp)::X2(1:GMAX),LPOLY(0:NMAX,0:LMAX,1:GMAX)
 REAL(dp)::alpha
 INTEGER::I,L
 LPOLY(:,:,:)=0.0D0
!   
 DO L=0,LUSE
    ALPHA=L+0.5D0
    DO I=1,GUSEX
       CALL laguerre_general(NUSE,ALPHA,X2(I),LPOLY(0:NUSE,L,I))
    ENDDO
 ENDDO     
 RETURN
END SUBROUTINE

FUNCTION XREAL(X,Y,A,B,SN) RESULT(RES)
USE PARS
IMPLICIT NONE
 REAL(DP)::X,Y,A,B,RES
 INTEGER::SN
 RES=0.25D0*(SQRT(X/A)+SN*SQRT(Y/B))**2
 RETURN
END FUNCTION XREAL

!SUBROUTINE XLNL2D(AA)!2D Mesh points -> Variable values
!USE PARS
!USE GAUSS
!USE LX2D
!IMPLICIT NONE
! INTEGER::I,J,SN,MSN
! REAL(DP)::AA
! REAL(DP)::A,B,XREAL
! A=AA+0.5D0;B=0.5D0;SN=1;MSN=-1
! DO I=1,GUSEX
!   DO J=1,GUSEY
!     X2D1(I,J)=XREAL(XMESH(I),YMESH(J),A,B,SN)
!     X2D2(I,J)=XREAL(XMESH(I),YMESH(J),A,B,MSN)
!     X2D3(I,J)=XREAL(XMESH(I),YMESH(J),B,A,SN)
!     X2D4(I,J)=XREAL(XMESH(I),YMESH(J),B,A,MSN)
!   ENDDO
! ENDDO
! RETURN
!END SUBROUTINE XLNL2D



!SUBROUTINE LNL2D(X2,LPOLY)! CONSTRUCT L_{nl}^{alpha} at each l, n, x2(I,J) point.
!USE PARS
!IMPLICIT NONE
! REAL(dp)::alpha
! REAL(dp)::X2(1:GMAX,1:GMAX),LPOLY(0:NMAX,0:LMAX,1:GMAX,1:GMAX)
! INTEGER::L,I,J
! LPOLY(:,:,:,:)=0.0D0
!    
! DO L=0,LUSE
!    ALPHA=L+0.5D0
!    DO I=1,GUSEX
!       DO J=1,GUSEY
!          CALL laguerre_general(NUSE,ALPHA,X2(I,J),LPOLY(:,L,I,J))
!       ENDDO
!    ENDDO
! ENDDO      
! RETURN
!END SUBROUTINE LNL2D

!SUBROUTINE LNL2S!L POLYNOMIAL AT DIFFERENT MESH POINTS SERIERS
!USE PARS
!USE LX2D
!IMPLICIT NONE
! CALL LNL2D(X2D1,L2D1)
! CALL LNL2D(X2D2,L2D2)
! CALL LNL2D(X2D3,L2D3)
! CALL LNL2D(X2D4,L2D4)
!END SUBROUTINE LNL2S

